config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("trello/", include("trello.urls")),
    path("trello/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
]

# Django側で定義されていたもの
# trello/login/
# trello/logout/

trello/urls.py
from django.urls import path
from . import views

app_name = 'trello'

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("users/<int:pk>/", views.UserDetailView.as_view(), name='user_detail'),

]

# trello/urls.pyで定義したもの
# trello/
# trello/home/
# trello/signup/

trello/models.py
from django.db import models

# Create your models here.

trello/views.py
from django.contrib.auth import login  # 追加
from django.contrib.auth.forms import UserCreationForm  # 追加
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect  # redirectをインポート
from django.views.generic import DetailView

# # Create your views here.
from django.http import HttpResponse


def index(request):
    return render(request, "trello/index.html")


@login_required
def home(request):
    return render(request, "trello/home.html")


def signup(request):
    if request.method == 'POST':
        print("会員照合するだよ")
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user_instance = form.save()
            login(request, user_instance)
            return redirect("trello:home")

    else:
        print('elseなのでGETだよ')
        print(request)
        context = {
            "form": UserCreationForm()
        }
        print(context)
        return render(request, 'trello/signup.html', context)


class UserDetailView(DetailView):
    model = User
    template_name = "trello/users/detail.html"

trello/templates/trello/base.html
<!doctype html>
<html lang="ja">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>trello</title>
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'trello:index' %}">trello</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        </ul>
        <ul class="navbar-nav">
          {% if request.user.is_authenticated %}
          <span class="navbar-text">
            こんにちは {{ request.user.username }} さん
          </span>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout'%}">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">ログイン</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'trello:signup' %}">サインアップ</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src=" https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

trello/templates/trello/home.html
{% extends "trello/base.html" %}

{% block content %}
<div class="container">
  <h1>サインアップ完了</h1>
  <p>サインアップが完了しました。</p>
</div>
{% endblock %}

trello/templates/trello/index.html
{% extends "trello/base.html" %}

{% block content %}
<div class="container">
  <h1 class="display-4">trello</h1>
  <p class="lead">trelloでタスク管理をしてみましょう。</p>
  <hr class="my-4">
  <p>このアプリケーションはDjangoで作られています。</p>
  <a class="btn btn-primary btn-lg" href="{% url 'login' %}" role="button">ログイン</a>
  <a class="btn btn-primary btn-lg" href="{% url 'trello:signup' %}" role="button">サインアップ</a>
</div>
{% endblock %}

trello/templates/trello/signup.html
{% extends "trello/base.html" %}

{% block content %}
<div class="container">
  <h1>サインアップ</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">登録</button>
  </form>
</div>
{% endblock %}

trello/templates/trello/users/detail.html
{% extends "trello/base.html" %}

{% block content %}
<div class="container">
  <h1>ユーザー詳細</h1>
    <dl class="row">
    <dt class="col-sm-3">ユーザー名</dt>
    <dd class="col-sm-9">{{ user.username }}</dd>
    <dt class="col-sm-3">姓</dt>
    <dd class="col-sm-9">{{ user.last_name }}</dd>
    <dt class="col-sm-3">名</dt>
    <dd class="col-sm-9">{{ user.first_name }}</dd>
    <dt class="col-sm-3">メールアドレス</dt>
    <dd class="col-sm-9">{{ user.email }}</dd>
  </dl>
</div>
{% endblock %}



sou